version: "3.8"

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FRONTEND_URL=http://localhost:5173
      - AUTH_SERVICE_URL=http://auth-service:8081
      - PRODUCT_SERVICE_URL=http://product-service:8082
      - ORDER_SERVICE_URL=http://order-service:8083
    depends_on:
      - auth-service
      - product-service
      - order-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGODB_URI=${AUTH_MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  product-service:
    build: ./services/product-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGODB_URI=${PRODUCT_MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_SECRET=${CLOUD_SECRET}
      - AUTH_SERVICE_URL=http://auth-service:8081

  order-service:
    build: ./services/order-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - MONGODB_URI=${ORDER_MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=http://auth-service:8081
      - PRODUCT_SERVICE_URL=http://product-service:8082
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - TWILIO_VERIFIED_NUMBER=${TWILIO_VERIFIED_NUMBER}
